---
- name: create WAR at build server
  hosts: build
  tasks:
    - name: Ensure that java is running
      install: default-jdk
      become: true
      roles: 
        - default-jdk

    - name: Ensure Git Repo is cloned
      git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/boxfuse-sample-java-war-hello
  
    - name: install maven
      become: yes
      roles: 
        - maven
    - name: run maven  
        shell: mvn package -f ./tmp/boxfuse-sample-java-war-hello/pom.xml
	  
    - name: Specifying a destination path
        fetch:
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war 
        dest: /tmp/prefix-{{ prod }}
        flat: yes
- name: run WAR at production server
  hosts: prod
  tasks:	
    - name: Ensure tomcat is running
        install: tomcat8
        become: yes
        script: ./bin/catalina.sh start
        args:
          chdir: etc/tomcat8
    - name: move WAR file to another server
      copy:
      src: /tmp
      dest: /var/lib/tomcat8/webapps		
    - name: Allow all access to tcp port 8080
      ufw:
      rule: allow
      port: '8080'
      proto: tcp	
    - name: restart tomcat
      service: tomcat
      state: restarted  
---	       
